server:
  port: 3000

############################################################################
spring:                          #Spring Config#                         ###
############################################################################
  # Devtool
  devtools:
    restart:
      enabled: true